# Generated by Django 2.2.3 on 2019-07-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atp', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('tournament', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('court', models.CharField(blank=True, max_length=50, null=True)),
                ('surface', models.CharField(blank=True, max_length=50, null=True)),
                ('round', models.CharField(blank=True, max_length=50, null=True)),
                ('bestof', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('loser', models.CharField(blank=True, max_length=50, null=True)),
                ('wrank', models.IntegerField(blank=True, null=True)),
                ('lrank', models.IntegerField(blank=True, null=True)),
                ('wpts', models.IntegerField(blank=True, null=True)),
                ('lpts', models.IntegerField(blank=True, null=True)),
                ('w1', models.IntegerField(blank=True, null=True)),
                ('l1', models.IntegerField(blank=True, null=True)),
                ('w2', models.IntegerField(blank=True, null=True)),
                ('l2', models.IntegerField(blank=True, null=True)),
                ('w3', models.IntegerField(blank=True, null=True)),
                ('l3', models.IntegerField(blank=True, null=True)),
                ('w4', models.IntegerField(blank=True, null=True)),
                ('l4', models.IntegerField(blank=True, null=True)),
                ('w5', models.IntegerField(blank=True, null=True)),
                ('l5', models.IntegerField(blank=True, null=True)),
                ('wsets', models.IntegerField(blank=True, null=True)),
                ('lsets', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('b365w', models.FloatField(blank=True, null=True)),
                ('b356l', models.FloatField(blank=True, null=True)),
                ('psw', models.FloatField(blank=True, null=True)),
                ('psl', models.FloatField(blank=True, null=True)),
                ('maxw', models.FloatField(blank=True, null=True)),
                ('maxl', models.FloatField(blank=True, null=True)),
                ('avgw', models.FloatField(blank=True, null=True)),
                ('avgl', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
