# Generated by Django 2.2.4 on 2019-08-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpmatch',
            name='away_r4',
            field=models.IntegerField(null=True),
        ),
    ]
