# Generated by Django 2.2.3 on 2019-07-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATPMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('round', models.CharField(max_length=20, null=True)),
                ('tournament', models.CharField(max_length=50, null=True)),
                ('winner', models.CharField(max_length=20, null=True)),
                ('loser', models.CharField(max_length=20, null=True)),
                ('w1', models.IntegerField(null=True)),
                ('l1', models.IntegerField(null=True)),
                ('w2', models.IntegerField(null=True)),
                ('l2', models.IntegerField(null=True)),
                ('w3', models.IntegerField(null=True)),
                ('l3', models.IntegerField(null=True)),
                ('w4', models.IntegerField(null=True)),
                ('l4', models.IntegerField(null=True)),
                ('w5', models.IntegerField(null=True)),
                ('l5', models.IntegerField(null=True)),
                ('wsets', models.IntegerField(null=True)),
                ('lsets', models.IntegerField(null=True)),
                ('totalsets', models.IntegerField(null=True)),
                ('totalgames', models.IntegerField(null=True)),
                ('bestof', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=50, null=True)),
                ('iswinhome', models.BooleanField(default=False, null=True)),
                ('waces', models.CharField(max_length=50, null=True)),
                ('wser1', models.IntegerField(null=True)),
                ('wser2', models.IntegerField(null=True)),
                ('wser', models.IntegerField(null=True)),
                ('wrec', models.IntegerField(null=True)),
                ('wtotal', models.IntegerField(null=True)),
                ('laces', models.CharField(max_length=50, null=True)),
                ('lser1', models.IntegerField(null=True)),
                ('lser2', models.IntegerField(null=True)),
                ('lser', models.IntegerField(null=True)),
                ('lrec', models.IntegerField(null=True)),
                ('ltotal', models.IntegerField(null=True)),
                ('b365w', models.FloatField(blank=True, null=True)),
                ('b356l', models.FloatField(blank=True, null=True)),
                ('psw', models.FloatField(blank=True, null=True)),
                ('psl', models.FloatField(blank=True, null=True)),
                ('maxw', models.FloatField(blank=True, null=True)),
                ('maxl', models.FloatField(blank=True, null=True)),
                ('ubw', models.FloatField(blank=True, null=True)),
                ('ubl', models.FloatField(blank=True, null=True)),
                ('bcw', models.FloatField(blank=True, null=True)),
                ('bcl', models.FloatField(blank=True, null=True)),
                ('avgw', models.FloatField(blank=True, null=True)),
                ('avgl', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
