# Generated by Django 2.2.4 on 2019-08-20 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_atpmatch_away_r4'),
    ]

    operations = [
        migrations.CreateModel(
            name='WTAMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('round', models.CharField(max_length=20, null=True)),
                ('tournament', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('winner', models.CharField(max_length=20, null=True)),
                ('loser', models.CharField(max_length=20, null=True)),
                ('home_r1', models.IntegerField(null=True)),
                ('away_r1', models.IntegerField(null=True)),
                ('home_r2', models.IntegerField(null=True)),
                ('away_r2', models.IntegerField(null=True)),
                ('home_r3', models.IntegerField(null=True)),
                ('away_r3', models.IntegerField(null=True)),
                ('home_r4', models.IntegerField(null=True)),
                ('away_r4', models.IntegerField(null=True)),
                ('home_r5', models.IntegerField(null=True)),
                ('away_r5', models.IntegerField(null=True)),
                ('home_winsets', models.IntegerField(null=True)),
                ('away_winsets', models.IntegerField(null=True)),
                ('totalsets', models.IntegerField(null=True)),
                ('totalgames', models.IntegerField(null=True)),
                ('bestof', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('home', models.CharField(max_length=50, null=True)),
                ('away', models.CharField(max_length=50, null=True)),
                ('home_aces', models.CharField(max_length=50, null=True)),
                ('home_doublefault', models.CharField(max_length=50, null=True)),
                ('home_ser1', models.IntegerField(null=True)),
                ('home_ser2', models.IntegerField(null=True)),
                ('homs_ser', models.IntegerField(null=True)),
                ('home_rec', models.IntegerField(null=True)),
                ('home_total', models.IntegerField(null=True)),
                ('away_aces', models.CharField(max_length=50, null=True)),
                ('away_doublefault', models.CharField(max_length=50, null=True)),
                ('away_ser1', models.IntegerField(null=True)),
                ('away_ser2', models.IntegerField(null=True)),
                ('away_ser', models.IntegerField(null=True)),
                ('away_rec', models.IntegerField(null=True)),
                ('away_total', models.IntegerField(null=True)),
                ('home_b365', models.FloatField(blank=True, null=True)),
                ('away_b356', models.FloatField(blank=True, null=True)),
                ('home_ps', models.FloatField(blank=True, null=True)),
                ('away_ps', models.FloatField(blank=True, null=True)),
                ('home_winamax', models.FloatField(blank=True, null=True)),
                ('away_winamax', models.FloatField(blank=True, null=True)),
                ('home_unibet', models.FloatField(blank=True, null=True)),
                ('away_unibet', models.FloatField(blank=True, null=True)),
                ('home_betclic', models.FloatField(blank=True, null=True)),
                ('away_betclic', models.FloatField(blank=True, null=True)),
                ('home_avg', models.FloatField(blank=True, null=True)),
                ('away_avg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='atpmatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atpmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
