# Generated by Django 2.2.4 on 2019-08-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190820_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.RenameField(
            model_name='atpmatch',
            old_name='away_b356',
            new_name='away_b365',
        ),
        migrations.RenameField(
            model_name='wtamatch',
            old_name='away_b356',
            new_name='away_b365',
        ),
    ]
