# Generated by Django 2.2.3 on 2019-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190731_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpmatch',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
