# Generated by Django 2.2.3 on 2019-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_atpmatch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpmatch',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
