# Generated by Django 2.2.4 on 2019-08-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20190822_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atpmatch',
            old_name='homs_ser',
            new_name='home_ser',
        ),
    ]
