# Generated by Django 2.2.4 on 2019-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20190823_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpmatch',
            name='court',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atpmatch',
            name='surface',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
