# Generated by Django 2.2.3 on 2019-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_atpmatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpmatch',
            name='ldfault',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atpmatch',
            name='wdfault',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
