# Generated by Django 2.2.4 on 2019-08-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20190824_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpmatch',
            name='away_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atpmatch',
            name='home_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtamatch',
            name='away_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtamatch',
            name='home_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
