# Generated by Django 2.2.4 on 2019-08-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20190826_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atpmatch',
            old_name='away_min',
            new_name='away_max',
        ),
    ]
