# Generated by Django 2.2.4 on 2019-08-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20190826_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atpmatch',
            name='loser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atpmatch',
            name='winner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wtamatch',
            name='loser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wtamatch',
            name='round',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wtamatch',
            name='winner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
