# Generated by Django 2.2.3 on 2019-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATPTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('series', models.CharField(max_length=50, null=True)),
                ('surface', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTATournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('series', models.CharField(max_length=50, null=True)),
                ('surface', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
