# Generated by Django 2.2.4 on 2019-08-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atptournament',
            name='nicknames',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wtatournament',
            name='nicknames',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
