# Generated by Django 2.2.4 on 2019-09-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20190817_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='atptournament',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='wtatournament',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
