# Generated by Django 2.2.3 on 2019-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATPPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('max_rank', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=50)),
                ('pts', models.IntegerField(null=True)),
                ('inc_pts', models.IntegerField(null=True)),
                ('dec_pts', models.IntegerField(null=True)),
                ('cur_tournament', models.CharField(max_length=50, null=True)),
                ('prev_tournament', models.CharField(max_length=50, null=True)),
                ('next_pts', models.IntegerField(null=True)),
                ('max_pts', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTAPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('max_rank', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=50)),
                ('pts', models.IntegerField(null=True)),
                ('inc_pts', models.IntegerField(null=True)),
                ('dec_pts', models.IntegerField(null=True)),
                ('cur_tournament', models.CharField(max_length=50, null=True)),
                ('prev_tournament', models.CharField(max_length=50, null=True)),
                ('next_pts', models.IntegerField(null=True)),
                ('max_pts', models.IntegerField(null=True)),
            ],
        ),
    ]
