# Generated by Django 2.2.4 on 2019-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atpplayer',
            name='nickname',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wtaplayer',
            name='nickname',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
