# Generated by Django 2.2.4 on 2019-08-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190808_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atpplayer',
            old_name='nickname',
            new_name='nicknames',
        ),
        migrations.RenameField(
            model_name='wtaplayer',
            old_name='nickname',
            new_name='nicknames',
        ),
    ]
